name = "Scotty's Coffee"
description = "A CMU-only platform designed to make networking between students feel less like collecting connections and more like having real conversations."

[[repos]]
name = "scotty-coffee"
description = "A CMU-only platform designed to make networking between students feel less like collecting connections and more like having real conversations."

[[membership]]
timeframe = "2026-2027"
leads = ["NainaEnock", "aanya21gupta"]

[[membership.members]]
github-username = "aanya21gupta"

[[membership.members]]
github-username = "janek0420"

[[membership.members]]
github-username = "kzz9984"

[[membership.members]]
github-username = "msarora-cyber"

[[membership.members]]
github-username = "NainaEnock"

[[membership.members]]
github-username = "RocketRules"

[[membership.members]]
github-username = "samad2084"

[[membership.members]]
github-username = "mamabhi"
