name = "Wiki"
description = "The Labrador Wiki team."
website = "https://wiki.scottylabs.org"
server = "https://api.wiki.scottylabs.org"

[[repos]]
name = "wiki"
description = "A Labrador Wiki agent"

[[membership]]
timeframe = "2026-2027"
leads = ["Yuxiang-Huang"]

[[membership.members]]
github-username = "Yuxiang-Huang"
